Jia li
revaturelabs/rideshare-frontend pull request #2
Opened 2020-01-02 21:16 UTC by carstonsrc

Making a pull request to dev so I can register dev branch with CircleCi.

2020-01-02 21:19 UTC, pnguye17 approved these changes

2020-01-02 21:19 UTC, andrewvoroshylo approved these changes

2020-01-03 14:42 UTC, carolynrehm commented on src/app/services/user-service/user.service.ts
> +	url: string = 'http://localhost:8080/users';
Let's start using the environment files to parameterize these value; this wont always be "localhost"

2020-01-09 14:45 UTC, carolynrehm commented on src/app/app.component.spec.ts
> +  // });
let's get this test to work rather than commenting it out @carstonsrc maybe you or someone else working on frontend testing can help w this

2020-01-09 14:47 UTC, carolynrehm commented on src/app/components/admin/admin.component.css
> +small {
is this used?

2020-01-09 15:17 UTC, carolynrehm commented on src/app/components/driver-register/driver-register.component.ts
> +	validatePhone() {
perhaps we could use a service here for validation rather than including this directly in the component

2020-01-09 15:42 UTC, carolynrehm commented on src/index.html
> +    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
can we include this as a npm dependency rather than in the index.html

2020-01-09 15:43 UTC, carolynrehm commented on src/app/services/user-service/user.service.ts
> +	url: string = 'http://localhost:8080/users/';
replace from environment

2020-01-09 15:44 UTC, carolynrehm commented on src/app/services/user-service/user.service.ts
> +		this.user.batch = this.batch;
are we using this variable before now? can we just instantiate batch here rather than create a separate instance variable?

2020-01-09 15:46 UTC, carolynrehm commented on src/app/services/car-service/car.service.ts
> +    url: string = 'http://localhost:8080/cars/';
env

2020-01-09 15:47 UTC, carolynrehm commented on src/app/services/car-service/car.service.ts
> +				console.warn(error);
can we replace these console.logs with a logging service? this could also be more descriptive about where the problem is occurring

2020-01-09 15:47 UTC, carolynrehm commented on src/app/services/batch-service/batch.service.ts
> +	url: string = 'http://localhost:8080/batches';
env

2020-01-09 15:53 UTC, carolynrehm commented on src/app/components/rider-register/rider-register.component.ts
> +		console.log(this.batchNum);
What is the purpose of this?

2020-01-09 15:54 UTC, carolynrehm commented on src/app/components/rider-register/rider-register.component.ts
> +	userName: string = '';
Why create these instance variables rather than just creating an User with a Batch?

2020-01-09 15:57 UTC, carolynrehm commented on src/app/components/preference/preference.component.ts
> +  isActive: boolean;
why not use the instance variables of the user variables?

2020-01-09 16:08 UTC, carolynrehm commented on src/app/components/profile/profile.component.html
> +                <td><img class="edit" (click)="edit('email')" src="../../../assets/pencil.png"/></td>
Assets shouldn't use relative paths. "assets/pencil.png" should render correctly and follows best practices

2020-01-09 16:10 UTC, carolynrehm requested changes
Overall this looks really good. We need a few changes before we can proceed:
- can we use the AuthService's user info to manage session, rather than accessing information in the sessionStorage?
- lets create a dev environment - dev service can be found at http://54.172.17.158 (on port 80, so there is no need to add any port - ping http://54.172.17.158/actuator/health for up status)
- remove documentation files from this pull request

2020-01-09 16:11 UTC, carolynrehm commented
also will need to resolve the merge conflict with package.json before we proceed with the merge

2020-01-09 16:34 UTC, carolynrehm commented
Also the icon used, while appropriate, is very small and difficult to read. Perhaps we can figure out an alternative

2020-01-10 18:37 UTC, carolynrehm commented
@DJSHS remove generated documentation files from this PR and pull from dev to get the circleci config file

2020-01-10 18:40 UTC, carolynrehm commented
@DJSHS changes look good

2020-01-13 14:25 UTC, carolynrehm commented on src/app/components/login/login.component.ts
> +	userName: string = '';
Why have these additional fields? Aren't they accessible through the "chosenUser" field?

2020-01-13 14:27 UTC, carolynrehm commented on src/app/components/login/login.component.ts
> +			this.userService.getAllUsers()
One major benefit of pagination is that the data processed on the frontend is reduced. This is fine for now, but will need to be refactored

2020-01-13 14:49 UTC, carolynrehm commented on src/app/components/profile/profile.component.ts
> +          setTimeout(() => this.updateFailed = false, 5000);
Why have both an update success and update failed? What is the purpose for the setTimeout for each?

2020-01-13 14:50 UTC, carolynrehm commented on src/app/components/driver-register/driver-register.component.ts
> +	user: User = new User();
Both here and in the rider register, why do we need a batch independent of the user? Doesn't the user already have a batch field?

2020-01-13 14:53 UTC, carolynrehm requested changes
@DJSHS Good changes, just a couple more questions in the comments and we should be good to merge in

2020-01-13 15:23 UTC, carolynrehm commented on src/app/components/profile/profile.component.ts
> +          setTimeout(() => this.updateFailed = false, 5000);
-- alert shows briefly and then disappears --

2020-01-13 15:23 UTC, carolynrehm commented on src/app/components/driver-register/driver-register.component.ts
> +	user: User = new User();
-- an instance of a batch object is to be assigned in the user model --

2020-01-13 15:24 UTC, carolynrehm commented on src/app/components/login/login.component.ts
> +			this.userService.getAllUsers()
-- just used visually for selection of users --

2020-01-13 15:24 UTC, carolynrehm commented on src/app/components/login/login.component.ts
> +	userName: string = '';
-- used for display/search --

2020-01-13 16:30 UTC, carolynrehm commented
@DJSHS making validationService constructor arg public and working with "car.seats" instead of just "seats" on line 11 of car-register html, will resolve your build issues and you should be ready to go

2020-01-13 18:56 UTC, carolynrehm approved these changes
Approving for merge, @DJSHS please make sure to address sonarcloud results

2020-01-13 18:57 UTC, merged