Feature 3.1
revaturelabs/rideshare-frontend pull request #20
Opened 2020-01-14 16:57 UTC by jasonyang1992

2020-01-14 17:00 UTC, andrewvoroshylo approved these changes

2020-01-14 17:00 UTC, DJSHS approved these changes

2020-01-14 17:00 UTC, pnguye17 approved these changes

2020-01-14 18:06 UTC, carolynrehm commented on src/app/components/admin/admin.component.ts
> +
@jasonyang1992  this functionality that is already found in the user service; can we consolidate this implementation into one service?

2020-01-14 18:07 UTC, carolynrehm commented on src/app/components/admin/admin.component.ts
> +  }
can we display this information without making an entirely new http call?

2020-01-14 18:09 UTC, carolynrehm commented on src/app/pipes/adminfilter.pipe.ts
> +  }
Angular advises against using pipes for searching and sorting ([see documentation here](https://angular.io/guide/pipes#appendix-no-filterpipe-or-orderbypipe)) - can we do this using a service method instead?

2020-01-14 18:11 UTC, carolynrehm requested changes
see comments

2020-01-15 14:11 UTC, carolynrehm requested changes
@jasonyang1992 resolve merge conflicts

2020-01-15 14:13 UTC, carolynrehm reviewed
Also, if possible remove changes from package.json and app.module.ts because they're not relevant. Tag me when you're ready for review

2020-01-15 15:04 UTC, carolynrehm commented on src/app/components/admin/admin.component.ts
> +    console.log(obj);
@jasonyang1992 
- remove console log here 
- is there a reason for passing all of these parameters in along with the user object? wouldn't all of those fields already be a part of the user object?

2020-01-15 15:29 UTC, carolynrehm commented on src/app/components/admin/admin.component.html
> +      <td *ngIf="get.batch">{{get.batch.batchNumber}}</td>
This ngIf makes things render inconsistently if there is no batch; puts "isActive" value in the batch column and the ban button in the "isActive" column

2020-01-15 15:58 UTC, carolynrehm commented on src/app/components/admin/admin.component.html
> +    <tr *ngFor="let get of listofUsers">
can we change this naming to something a little more intuitive? perhaps "let user of users" having users represent the list of users?

2020-01-15 15:59 UTC, carolynrehm commented on src/app/components/admin/admin.component.html
> +      <td *ngIf="get.batch">{{get.batch.batchNumber}}</td>
we can use a ternary here to check if the batch exists and assigning the string interpolated value to the batch number if it does, or "n/a" if it doesnt

2020-01-15 18:20 UTC, carolynrehm approved these changes

2020-01-15 18:21 UTC, carolynrehm commented
@jasonyang1992 merge conflict needs resolution before I can merge

2020-01-15 18:33 UTC, carolynrehm approved these changes

2020-01-15 18:33 UTC, merged